[workspace]
members = [
    "crates/sobol"
]

[package]
name = "iris"
version = "0.1.0"
authors = ["Matt Taylor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.3"
bvh = "0.3.2"
num_cpus = "1.12.0"
statrs = "0.12.0"
sobol = { path = "crates/sobol" }
