[workspace]
members = [
    "crates/sobol"
]

[package]
name = "iris"
version = "0.1.0"
authors = ["Matt Taylor"]
edition = "2018"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
debug = true
codegen-units = 1

[dependencies]
minifb = "0.15.3"
num_cpus = "1.12.0"
sobol = { path = "crates/sobol" }
enum_dispatch = "0.2.2"
image = "0.23.3"
